### ISSUE TITLE
Possible bug in SU Activated/deactivated tile status 

### ISSUE THREAD

**Issue by YUDHPK** [bhb27/isu#13]
When we view the tile in quick settings it requests for SuperUser permission to perform its required work but when we close the quick  tile panel it doesnt surrender(close the shell) SU permisssion .

To revoke permission i.e. close its shell we have to open the app and remove it from recents

What it should do ?
it should override onStopListening() method in QuickTileSU.java file to close the Root shell
https://developer.android.com/reference/android/service/quicksettings/TileService.html#onStartListening()

**Comment by fgl27** [comment]
onStopListening() does it, widgets also need a close

thanks... :+1:

**Comment by fgl27** [comment]
If there is something else let me know...

**Comment by YUDHPK** [comment]
For your build.prop section there are options as  
Known safe value and unsafe value
But there should be an option to set it to original values also .
And an option to backup build.prop in the same folder as original because if something goes wrong and device doesn't boot then a user can rename the backup file to original

**Comment by YUDHPK** [comment]
And by the way i am same person who contacted on your email 2 days ago 
About similar su problems and about the ro.boot.warranty_bit = 0  prop safe value

**Comment by fgl27** [comment]
I released how you are...

A b.p backup is not easy to make on a way user can understand, because when will I make one? how I will tell the user?
As it never fail before I expect it to be 100% as I don't depend from outside tools to edit is all with in the app...

anything save to the app folder will be erased when a clean of app data, save to system will be lost on it nightly flash... necessary to redo...

To do something flow less and with the user aware is not easy, if you can think on a logical way try me we can try to make something work, but only if is flawless...

I really think is not necessary the section is flawless, if user change it in a way it need to return because it fails, or he wanna the original value even they are bad values that make none ROOT apps to fail, he can just re-flash the last ROM zip delete the data/data/ folder of iSu and it will be 100%...

any way try me...

:+1:

**Comment by YUDHPK** [comment]
when i change a value of a prop using force value into build.prop file option(checkbox)
the app appends the value in build.prop file (if a beginner or tester changes this value to something bad then he will need a backup of the file which he can use to recover and rename using recovery)
at that instance you can create a backup using the cp command from android shell  into the same system folder but renamed as build.prop.bak
when you show the message that some values are only applied after a reboot at the same instance notify the user

**Comment by fgl27** [comment]
" (if a beginner or tester changes this value to something bad then he will need a backup of the file which he can use to recover and rename using recovery)"

a beginner user doesn't even know how to find and change a file name in twrp, even if you tell how to they will have a hard time.

the best solution is and always will be re-flash current ROM .zip on trouble all user know that and it will not cause other problems, this app is to be used on a ROM that is always shared via .zip so the user must have it on the device or something that was used to flash the first time.

I can do a function to check if a backup exist if not make one, after boot up or the first time the app is open.
